"""empty message

Revision ID: 37f1f81ad6fd
Revises: 29108481baa5
Create Date: 2020-08-04 12:21:42.515824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f1f81ad6fd'
down_revision = '29108481baa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ArtistGenreAssociation',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id')
    )
    op.drop_constraint('Genre_artist_id_fkey', 'Genre', type_='foreignkey')
    op.drop_column('Genre', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Genre', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Genre_artist_id_fkey', 'Genre', 'Artist', ['artist_id'], ['id'])
    op.drop_table('ArtistGenreAssociation')
    # ### end Alembic commands ###
